server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /api

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        auto_quote_keyword: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        storage_engine: innodb
        format_sql: true
    generate-ddl: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:usedcar;MODE=MySQL;
    username: sa
    password:

  flyway:
    enabled: false

  h2:
    console:
      enabled: true

  config:
    import:
      - classpath:application-env.yml

  main:
    allow-bean-definition-overriding: true

  jackson:
    property-naming-strategy: SNAKE_CASE
